### ISSUE TITLE
having .prettierrc at root level of the project creates an error with CHANGELOG generation step

### ISSUE THREAD

**Issue by azimqordoba** [ridedott/release-me-action#410]
I have a `.prettierrc` at root level of my project with "parser" set as "typescript".
This results in error below:

![image](https://user-images.githubusercontent.com/53835880/99759400-2818e000-2ab8-11eb-973a-965291a15efd.png)

Any idea how I can bypass this ?

**Comment by merlinnot** [comment]
Hi! Prettier automatically infers the parser from the input file path, so you shouldn’t have to change this setting. If you have a need for it, I'd suggest one of two things:
- Add a `--parser` flag to your npm script for formatting instead of setting it in `.prettierrc`.
- Contribute to this repository with an addition of `--parser markdown`, if command line flags override settings in `.prettierrc` (you'd need to test that).

**Comment by acazacu** [comment]
@azimqordoba If you use the latest version of the action now, prettier explicitly runs on the CHANGELOG.md file with the `markdown` parser. Your issue should be resolved.

If you have any further comments, please let me know, otherwise, I'm going to close this issue at the end of next week.
